[project]
name = "auto-mile"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.auto_mile]
path = "contracts/auto_mile.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
